### ISSUE TITLE
[Question] Direct messages

### ISSUE THREAD

**Issue by franciskim** [xBytez/slackbotapi#11]
Hi all, great work on the code! 

Is there a way to know if a message sent is a direct message?

**Comment by xBytez** [comment]
Hey there Francis,

Thank you so much for the kind words! Yes, there is! I just found how Slack has different types of messages. Every message you receive has the channel string in the message object. The type of message/where it comes from is prefixed by the first lettter.

Example:
```{"type":"message","channel":"D036EKLUS","user":"U02DZGVLA","text":"Hey","ts":"1437220631.000003","team":"SOMECOOLTEAMID"}```

This is a DM, you can tell it's a DM by the first letter in the channel ID being a D.

```public channel = C (ex: C02MFJKL7)
private group = G (ex: G02MNL0K6)
DM/PM = D (ex: D036EKLUS)```

**Comment by franciskim** [comment]
aha! I have a lot of learning to do from your code... that's perfect, thanks again! :+1:

**Comment by xBytez** [comment]
You're welcome!

If you want to check another way you could also do the following:

```javascript
slack.on('message', function(data) {
    if (slack.getIM(data.channel) !== null && slack.getIM(data.channel).is_im) {
      //DM MAGIC!
    }
}
```

I'm not a 100% sure if that will work but you could test that if you prefer checking like that.
