### ISSUE TITLE
"recieved" spelled wrong in log message

### ISSUE THREAD

**Issue by ghostsquad** [xBytez/slackbotapi#20]
`23:09 56s 943ms [Transport] [SlackAPI]      Recieved: {"type":"hello"}`

**Comment by xBytez** [comment]
Wow! You're right! Nice find. Sorry, obviously this shows that English isn't my native language. I'll fix it now!

**Comment by xBytez** [comment]
Fixed!

**Comment by ghostsquad** [comment]
Awesome! :+1:
