### ISSUE TITLE
request: support for attachments

### ISSUE THREAD

**Issue by ghostsquad** [xBytez/slackbotapi#24]
https://api.slack.com/docs/attachments

**Comment by xBytez** [comment]
>The RTM API only supports posting simple messages formatted using our default message formatting   mode. It does not support attachments or other message formatting modes. To post a more complex   message as a user clients can call the chat.postMessage Web API method with as_user set to true. 

-- https://api.slack.com/rtm

HOWEVER! In the API there is a way to send requests using the Web API method. I added this to my commands switch.

    case "debugpost":
        var payload = {
            "attachments": [
                {
                    "fallback": "Fall back for notificaiton",
                    "pretext": "PRETEXT",
                    "title": "TITLE",
                    "title_link": "TITLE LINK",
                    "text": "woo! attachments",
                    "color": "#7CD197"
                }
            ],
            "username": "USERNAME",
            "channel": data.channel,
            "icon_url": "http://i.imgur.com/hAfHdi3.png"
        };
        slack.reqAPI('chat.postMessage', payload, function(data) {
            // do stuff
        });
    break;

![Screenshot](https://xbytez.eu/i/d/2015-08-28_23-09-56.png)

I hope this is what you wanted.

**Comment by ghostsquad** [comment]
This is exactly what I was looking for. Thanks!
