### ISSUE TITLE
HTML Example using slackboxapi

### ISSUE THREAD

**Issue by cmacdonnacha** [xBytez/slackbotapi#3]
Hi,

It would be great if you could add an example HTML page using this API. I'm trying to use it at the moment but I keep getting the following error: "Uncaught ReferenceError: require is not defined".

I would be greatly appreciated if you could add this example to clear things up on how we can implement this into a web app.

Thanks,
Cathal.

**Comment by xBytez** [comment]
Dear Cathal,

The error you are specifying is quite odd (if you're using node.js). Please note that this is a node.js module, and not a JavaScript script for in your browser. 

Kind regards,
xBytez

**Comment by IgorAntun** [comment]
Hey,

It seems like you're trying to use a node.js module in your browser, which wouldn't work. If you really need to do so, I think you should take a look at [Node Browserify](https://github.com/substack/node-browserify). It makes node.js modules accessible on the browser.

Cheers,
Igor Antun

**Comment by cmacdonnacha** [comment]
Ok great thanks.
