### ISSUE TITLE
presence_change events being blocked

### ISSUE THREAD

**Issue by magroski** [xBytez/slackbotapi#40]
I was testing multiple events using your code and I noticed that this block of code
```javascript 
} else if (data.type === 'presence_change') {
   // update slackData presence when user becomes active/inactive
   for (var i in self.slackData.users) {
      if (self.slackData.users[i].id === data.user) {
         self.slackData.users[i].presence = data.presence;
         break;
      }
   }
}
```
is blocking the bot from processing `presence_change` events.

Adding `cb(null, messageData);` after the for loop easily solve this problem.

https://github.com/xBytez/slackbotapi/blob/master/lib/rtm.js#L240

**Comment by franciskim** [comment]
looking back that seems like the sensible thing to do, thanks for bringing that up! @magroski

**Comment by magroski** [comment]
Don't forget to push the changes to npm :)

**Comment by xBytez** [comment]
I wont! I'm still working on a bit of documentation and I'll then update npm with the new version!
