### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by xBytez** [xBytez/slackbotapi#69]
This project has gotten kind of stale with out-of-date dependencies. It still works but could use some updates. 

**Feel free to look at the other issues too.**

This renders the greenkeeper bot PRs useless. You can ignore them and create one PR with all dependencies updated. Please extensively test before submitting PRs.

**Comment by luizbaldi** [comment]
Hi! Can I take a look at this issue? 😄

**Comment by gerlis18** [comment]
Updated libs ;).

**Comment by xBytez** [comment]
@luizbaldi Feel free to take a look. No need to ask :)

**Comment by xBytez** [comment]
Closed by #70. Thanks a lot @gerlis18.
