### ISSUE TITLE
Header image for README.md

### ISSUE THREAD

**Issue by xBytez** [xBytez/slackbotapi#71]
I feel like our README could use an image to further improve the looks of the README. Also a good hacktoberfest entry. No need to ask, feel free to submit a PR.

Feel free to take a look at the other issues as well.

**Comment by thanhcng** [comment]
I'd like to work on this pls

**Comment by xBytez** [comment]
Sorry @thanhcng ! @waynekata already submitted their PR. Thanks for your interest!

Closed. Done in #73.
