### ISSUE TITLE
Bugs in logger initialization

### ISSUE THREAD

**Issue by rubenvereecken** [xBytez/slackbotapi#8]
There are a couple of fishy things going on when initializing the logger. I'll try a workaround for the moment, but you may want to check out this code.

        logger = true;
        logger.init();

https://github.com/xBytez/slackbotapi/blob/master/index.js#L89

**Comment by Hunchmun** [comment]
I can only assume that 'logger' should be 'logging'

**Comment by xBytez** [comment]
Thanks both of you! Fixed, committed & pushed to npm/git.
